import { StyleSheet } from 'react-native';

export const homeScreenStyles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: '#63E2C6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 0,
    marginTop: -300,
  },
  logoLarge: {
    width: 380,
    height: 380,
    resizeMode: 'contain',
    marginBottom: -100,
    marginLeft: 4,
  },
  card: {
    width: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 28,
    elevation: 4,
    alignItems: 'center',
    marginTop: -30,
  },
  title: {
    fontFamily: 'AgencyFB',
    fontSize: 28,
    fontWeight: 'bold',
    color: '#222B45',
    marginBottom: 24,
    textAlign: 'center',
  },
  toggleRow: {
    flexDirection: 'row',
    backgroundColor: '#F5F5F7',
    borderRadius: 24,
    marginBottom: 20,
    padding: 4,
  },
  toggle: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 20,
    alignItems: 'center',
  },
  selectedToggle: {
    backgroundColor: '#63E2C6',
    shadowColor: '#63E2C6',
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  toggleText: {
    fontFamily: 'AgencyFB',
    color: '#222B45',
    fontWeight: '600',
    fontSize: 16,
  },
  input: {
    width: '100%',
    backgroundColor: '#F5F5F7',
    borderRadius: 16,
    padding: 14,
    fontSize: 18,
    color: '#222B45',
    marginBottom: 10,
    borderWidth: 0,
  },
  warning: {
    fontFamily: 'AgencyFB',
    color: '#FF9500',
    marginBottom: 8,
    fontSize: 15,
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#007AFF',
    paddingVertical: 16,
    borderRadius: 16,
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
    shadowColor: '#007AFF',
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  buttonText: {
    fontFamily: 'AgencyFB',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  secondaryButton: {
    backgroundColor: '#34C759',
    paddingVertical: 14,
    borderRadius: 16,
    width: '100%',
    alignItems: 'center',
    marginTop: 4,
  },
  secondaryButtonText: {
    fontFamily: 'AgencyFB',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  infoButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
    backgroundColor: '#F5F5F7',
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  infoButtonText: {
    fontSize: 20,
    color: '#007AFF',
  },
  logo: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    marginBottom: 100,
  },
}); 